<choose_a_name>:
    - name: "<choose_a_name>"
    - env-url: "https://<your_dt_domain>/"
    - env-token-name: "MONACO_TOKEN" # as set in the environment variable

# <choose_a_2nd_name>:
#    - name: "<choose_a_2nd_name>"
#    - env-url: "https://<your_2nd_dt_domain>"
#    - env-token-name: "<MONACO_SECOND_TOKEN>"
